### ISSUE TITLE
Accessing fastq files from raw uBiome zips

### ISSUE THREAD

**Issue by vsaraswathula** [dhimmel/fratjuice#11]
I am having trouble accessing the fastq files that are in the raw uBiome zip files. Using standard file extraction doesn't work because unzipping XXXXX.zip will produce XXXXX.zip.cpgz. Attempting to open XXXXX.zip.cpgz produces another XXXXX.zip file, leading to a frustrating cycle.

In the "fastq" branch of the repository, there are fastq.gz files for forward and reverse reads that I was able to open and analyze in R, so there must be a way to access these files--I just cannot figure it out.

**Comment by dhimmel** [comment]
Interesting. I've never heard of this issue, but it seems like it [could occur](http://osxdaily.com/2013/02/13/open-zip-cpgz-file/) from a variety of problems. My guess is that the files you're accessing in the `master` branch are not actually zip files. Instead they are text files with the Git LFS files information.

Git LFS is what we use for  "large file storage". If you don't have it installed on your computer, I think that you may have ended up downloading a text file rather than the actual binary zip archive. If you install [git LFS](https://git-lfs.github.com/) and then clone the repository, I am hoping that fixes the issue.

**Comment by vsaraswathula** [comment]
This did indeed fix the issue! I installed git LFS and have accessed the forward and reverse reads in the `master` branch's zips. Thank you!
